[build]
  command = "yarn build"
  publish = "dist"
  environment = { NODE_VERSION = 12, NODE_ENV = "production" }
[build.environment]
  NODE_VERSION = 12

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
